In [2]:
import random
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import random

class Cell:
    def __init__(self, x, y, state):
        self.x = x
        self.y = y
        self.state = state

    def __repr__(self):
        return f"Cell({self.x}, {self.y}, {self.state})"

class Grid:
    def __init__(self, n,cells, fire_spread_chance, burnout_chance, regrow_alone_chance, regrow_neighbor_chance, fully_regrow_chance):
        self.n = n
        self.fire_spread_chance = fire_spread_chance
        self.burnout_chance = burnout_chance
        self.regrow_alone_chance = regrow_alone_chance
        self.regrow_neighbor_chance = regrow_neighbor_chance
        self.fully_regrow_chance = fully_regrow_chance
        self.cells = cells
        # print(cells[np.ix_(range(3, 60, 3), range(0, 60, 3))])
        

    def __repr__(self):
        return f"Grid({self.n}, {self.fire_spread_chance}, {self.burnout_chance}, {self.regrow_alone_chance}, {self.regrow_neighbor_chance}, {self.fully_regrow_chance})"

    def transition(self):
        new_grid = np.zeros((self.n, self.n), dtype=np.int32)
        for x in range(self.n):
          for y in range(self.n):
            curr_state = self.cells[x][y]
            if curr_state == 1:
                # print("X<Y",x,y) 
                for neighbor in self.get_neighbors(x, y):
                    # print(neighbor)
                    i, j = neighbor
                    if new_grid[i][j] == 0 and random.random() < self.fire_spread_chance:
                        new_grid[i][j] = 1
                if random.random() < self.burnout_chance:
                        new_grid[x][y] = 2
            elif curr_state == 2 and random.random() < self.regrow_alone_chance:
                new_grid[x][y] = 3
            elif curr_state == 3:
                for neighbor in self.get_neighbors(x, y):
                    i, j = neighbor
                    if new_grid[i][j] == 2 and random.random() < self.regrow_neighbor_chance:
                        new_grid[i][j] = 3
                if random.random() < self.fully_regrow_chance:
                    new_grid[x][y] = 0
        self.cells=new_grid
        return new_grid
    def visualize(self):
      fig, ax = plt.subplots(figsize=(6, 6))
      mat = ax.matshow(self.cells, cmap="RdYlGn_r")
      
      def update(frame):
          new_grid=self.transition()
          print(new_grid)
          mat.set_data(new_grid)
          return [mat]
      
      ani = animation.FuncAnimation(fig,update, interval=50, save_count=50)
      plt.close(fig)
      return ani

    def get_neighbors(self, x, y):
        neighbors = []
        for i in range(-1, 2):
            for j in range(-1, 2):
                if 0 <= x + i < self.n and 0 <= y + j < self.n:
                    neighbors.append((x + i, y + j))
        # print(neighbors)
        return neighbors

def get_states(self):
    return [[cell.state for cell in row] for row in self.cells]
N = 100
ON = 300
BURNT = 200
GROWING = 100
OFF = 0
FIRE_SPREAD_CHANCE = 0.2
BURNOUT_CHANCE = 0.5
REGROW_ALONE_CHANCE = 0.05
REGROW_NEIGHBOR_CHANCE = 0.02
FULLY_REGROW_CHANCE = 0.01
cells = np.zeros((N, N))
cells[np.ix_(range(3, 60, 3), range(0, 60, 3))] = 1
grid = Grid(N,cells, FIRE_SPREAD_CHANCE, BURNOUT_CHANCE, REGROW_ALONE_CHANCE, REGROW_NEIGHBOR_CHANCE, FULLY_REGROW_CHANCE)


ani = grid.visualize()

# Display animation
from IPython.display import HTML
HTML(ani.to_jshtml())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 1 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 1 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 2 1 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [2 2 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 0 0 0]
 [0 2 2 ... 0 0 0]
 [